# Generated by Django 5.2.13 on 2026-04-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafetable',
            name='qr_custom_image',
            field=models.ImageField(blank=True, help_text='Optional: your own printed QR image. If empty, the app generates a QR from the ordering URL.', null=True, upload_to='table_qr/'),
        ),
    ]
