# Generated by Django 5.2.13 on 2026-04-29 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='menu_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo', to='cafe.menuitem'),
        ),
    ]
